export {default as Dashboard } from './Dashboard'
export {default as Account } from './Account'
export {default as Tables } from './Tables'
export {default as ProductCreateForm } from './CreateProduct'
export {default as Notifications } from './Notifications'
export {default as Appearance } from './Appearance'
export {default as Favourites } from './Favourites'