export {default as Home } from './Home'
export {default as Explore } from './Explore'
export {default as Deals } from './Deals'
export {default as ProductDetails } from './ProductDetails'
export {default as NotFound } from './NotFound'
export {default as Cart } from './Cart'
export {default as CkeckoutSuccess } from './CkeckoutSuccess'